FROM registry.access.redhat.com/ubi8/ubi:latest

RUN yum update -y && \
    yum install -y wget && \
     yum install -y curl 

WORKDIR /store

RUN mkdir checkpoints && \
    mkdir indexes && \
    mkdir models

USER 2000 
    