
apiVersion: v1
kind: Service
metadata:
  name: reranker-nlb
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: reranker
  ports:
   - name: http
     protocol: TCP
     port: 50052
     targetPort: 50052